name: Docker

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
  MM_NOTIFY_URL: "${{ secrets.MM_NOTIFY_URL }}"
  SEND_KEY: "${{ secrets.SEND_KEY }}"

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Check out code
      uses: actions/checkout@v4

    - name: Build and push image to ACR EE
      run: |
        #docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $REGISTRY
        #sh pull.sh
        data=`cat trigger.txt`

        if [ $MM_NOTIFY_URL ];then
          curl "https://wecomchan.wangbq.win:9104/wecomchan?sendkey=oR5yL6zT4gQ4eC3fK8&msg={同步成功 $data}&msg_type=text"
        else
          echo 'MM_NOTIFY_URL not set'
        fi
